#controls code generation using Dart’s build_runner system

#Builders are usually packages or plugins that generate Dart code automatically based on annotations or specific source files.


targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/model/**/*.dart
          - lib/src/**/*_models.dart
      freezed:
        generate_for:
          - lib/src/model/**/*.dart
          - lib/src/**/*_models.dart
        options:
          from_json: false
          to_json: false
      riverpod_generator:
        generate_for:
          - lib/src/localizations.dart
          - lib/src/model/**/*.dart
          - lib/src/network/*.dart
          - lib/src/db/*.dart
          - lib/src/**/*_providers.dart
