// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux; 
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbM-UHd6AAxKd_r5nIzmAzH2KUSgw0hEs',
    appId: '1:482089823583:android:32bba582f70e7540875aea',
    messagingSenderId: '482089823583',
    projectId: 'citystat1-791d8',
    storageBucket: 'citystat1-791d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ioz7GMLrGHgmTbi0n2bkfhaxYo9zzfs',
    appId: '1:482089823583:ios:7178b80acf3fb172875aea',
    messagingSenderId: '482089823583',
    projectId: 'citystat1-791d8',
    storageBucket: 'citystat1-791d8.firebasestorage.app',
    iosBundleId: 'org.Lichess.mobileV2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqubwhCsoH29q2d-s_DiPZlyqtGKUV8XM',
    appId: '1:482089823583:web:f6029e2c078d49aa875aea',
    messagingSenderId: '482089823583',
    projectId: 'citystat1-791d8',
    authDomain: 'citystat1-791d8.firebaseapp.com',
    storageBucket: 'citystat1-791d8.firebasestorage.app',
    measurementId: 'G-8872N4492R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ioz7GMLrGHgmTbi0n2bkfhaxYo9zzfs',
    appId: '1:482089823583:ios:9746a6f8019c5244875aea',
    messagingSenderId: '482089823583',
    projectId: 'citystat1-791d8',
    storageBucket: 'citystat1-791d8.firebasestorage.app',
    iosBundleId: 'org.Lichess.lichessMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqubwhCsoH29q2d-s_DiPZlyqtGKUV8XM',
    appId: '1:482089823583:web:d7f1c9d055f2cfb9875aea',
    messagingSenderId: '482089823583',
    projectId: 'citystat1-791d8',
    authDomain: 'citystat1-791d8.firebaseapp.com',
    storageBucket: 'citystat1-791d8.firebasestorage.app',
    measurementId: 'G-71JH7Q1JSX',
  );

  static const FirebaseOptions linux = FirebaseOptions(
  apiKey: 'AIzaSyDqubwhCsoH29q2d-s_DiPZlyqtGKUV8XM',
  appId: '1:482089823583:web:d7f1c9d055f2cfb9875aea',
  messagingSenderId: '482089823583',
  projectId: 'citystat1-791d8',
  authDomain: 'citystat1-791d8.firebaseapp.com',
  storageBucket: 'citystat1-791d8.firebasestorage.app',
  measurementId: 'G-71JH7Q1JSX',
);

}